name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up OpenJDK 11
      uses: joschi/setup-jdk@v1.0.0
      with:
        java-version: openjdk11
    - name: Build with Maven
      run: mvn -B package --file pom.xml
